activity_categories = [
    "Adventure",
    "Nature & Wildlife",
    "Water Activities",
    "Winter & Snow",
    "Cultural & Heritage",
    "Arts & Crafts",
    "Food & Culinary",
    "Festivals & Events",
    "Wellness & Relaxation",
    "Sports & Recreation",
    "Leisure & Entertainment",
    "Shopping & Markets",
    "Volunteer & Community",
    "Business & Networking",
    "Eco & Sustainable Travel",
    "Digital & Tech-Enabled Experiences"
]

airports = {
  'Agartala': 'IXA',
  'Agatti': 'AGX',
  'Agra': 'AGR',
  'Ahmedabad': 'AMD',
  'Aizawl': 'AJL',
  'Akola': 'AKD',
  'Allahabad': 'IXD',
  'Along': 'IXV',
  'Amritsar': 'ATQ',
  'Aurangabad': 'IXU',
  'Bagdogra': 'IXB',
  'Balurghat': 'RGH',
  'Bangalore': 'BLR',
  'Bareilly': 'BEK',
  'Belgaum': 'IXG',
  'Bellary': 'BEP',
  'Bhatinda': 'BUP',
  'Bhavnagar': 'BHU',
  'Bhopal': 'BHO',
  'Bhubaneswar': 'BBI',
  'Bhuj': 'BHJ',
  'Bikaner': 'BKB',
  'Bilaspur': 'PAB',
  'Car Nicobar': 'CBD',
  'Chandigarh': 'IXC',
  'Chennai': 'MAA',
  'Cochin': 'COK',
  'Coimbatore': 'CJB',
  'Cooch Behar': 'COH',
  'Cuddapah': 'CDP',
  'Daman': 'NMB',
  'Daporijo': 'DEP',
  'Darjeeling': 'DAI',
  'Dehradun': 'DED',
  'Dhanbad': 'DBD',
  'Dibrugarn': 'DIB',
  'Dimapur': 'DMU',
  'Div': 'DIU',
  'Durgapur': 'RDP',
  'Gawahati': 'GAU',
  'Gaya': 'GAY',
  'Goa': 'GOI',
  'Gorakhpur': 'GOP',
  'Guna': 'GUX',
  'Gwalior': 'GWL',
  'Hissar': 'HSS',
  'Hubli': 'HBX',
  'Hyderabad': 'HYD',
  'Imphal': 'IMF',
  'Indore': 'IDR',
  'Jabalpur': 'JLR',
  'Jagdalpur': 'JGB',
  'Jaipur': 'JAI',
  'Jaisalmer': 'JSA',
  'Jamnagar': 'JGA',
  'Jamshedpur': 'IXW',
  'Jeypore': 'PYB',
  'Jodhpur': 'JDH',
  'Jommu': 'IXJ',
  'Jorhat': 'JRH',
  'Kailashahar': 'IXH',
  'Kamalpur': 'IXQ',
  'Kandla': 'IXY',
  'Kangra': 'DHM',
  'Kanpur': 'KNU',
  'Keshod': 'IXK',
  'Khajuraho': 'HJR',
  'Khowai': 'IXN',
  'Kolhapur': 'KLH',
  'Kolkata': 'CCU',
  'Kota': 'KTU',
  'Kozhikode': 'CCJ',
  'Kullu Manali': 'KUU',
  'Latur': 'LTU',
  'Leh': 'IXL',
  'Lilabari': 'IXI',
  'Lucknow': 'LKO',
  'Ludhiana': 'LUH',
  'Madurai': 'IXM',
  'Malda': 'LDA',
  'Mangalore': 'IXE',
  'Mohanbari': 'MOH',
  'Mumbai': 'BOM',
  'Muzaffarnagar': 'MZA',
  'Muzaffarpur': 'MZU',
  'Mysore': 'MYQ',
  'Nagpur': 'NAG',
  'Nanded': 'NDC',
  'Delhi': 'DEL',
  'Neyveli': 'NVY',
  'Osmanabad': 'OMN',
  'Pantnagar': 'PGH',
  'Pasighat': 'IXT',
  'Pathankot': 'IXP',
  'Patna': 'PAT',
  'Pondicherry': 'PNY',
  'Porbandar': 'PBD',
  'Port Blair': 'IXZ',
  'Pune': 'PNQ',
  'Puttaparthi': 'PUT',
  'Raipur': 'RPR',
  'Rajahmundry': 'RJA',
  'Rajkot': 'RAJ',
  'Rajouri': 'RJI',
  'Ramagundam': 'RMD',
  'Ranchi': 'IXR',
  'Ratnagiri': 'RTC',
  'Rewa': 'REW',
  'Rourkela': 'RRK',
  'Rupsi India': 'RUP',
  'Salem': 'SXV',
  'Satna': 'TNI',
  'Shillong': 'SHL',
  'Shimla': 'SLV',
  'Silchar': 'IXS',
  'Solapur': 'SSE',
  'Srinagar': 'SXR',
  'Surat': 'STV',
  'Tezpur': 'TEZ',
  'Tezu': 'TEI',
  'Thanjavur': 'TJV',
  'Thiruvananthapuram': 'TRV',
  'Thoothukudi': 'TCR',
  'Tiruchirapally': 'TRZ',
  'Tirupati': 'TIR',
  'Vadodara': 'BDQ',
  'Varanasi': 'VNS',
  'Vijayanagar': 'VDY',
  'Vijayawada': 'VGA',
  'Vishakhapatnam': 'VTZ',
  'Warrangal': 'WGC',
  'Zero': 'ZER'
}
